//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySoundLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySoundLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE DATABASE my_sound_lib DEFAULT COLLATE utf8_general_ci;
        ///USE my_sound_lib;
        ///
        ///CREATE TABLE albums
        ///(
        ///  album_id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
        ///  album_name text NOT NULL,
        ///  title_song int(11) DEFAULT NULL,
        ///  album_thumbnail mediumblob
        ///) ENGINE=InnoDB;
        ///
        ///CREATE TABLE artists
        ///(
        ///  artist_id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
        ///  artist_name text NOT NULL
        ///) ENGINE=InnoDB;
        ///
        ///
        ///CREATE TABLE genres
        ///(
        ///  genre_id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
        ///  genre_name text NOT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string create_my_sound_lib {
            get {
                return ResourceManager.GetString("create_my_sound_lib", resourceCulture);
            }
        }
    }
}
